fail-on-severity: "low"
warn-only: false
fail-on-scopes: "runtime"
vulnerability-check: true
license-check: true
comment-summary-in-pr: "always"
show-openssf-scorecard: true
show-patched-versions: true
